In [21]:
import pandas as p
data = p.read_csv("dataset/supermarket_data.csv")
data.head(15)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01/12/10 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01/12/10 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01/12/10 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01/12/10 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01/12/10 08:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,01/12/10 08:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,01/12/10 08:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,01/12/10 08:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,01/12/10 08:28,1.85,17850.0,United Kingdom
9,536368,22960,JAM MAKING SET WITH JARS,6,01/12/10 08:34,4.25,13047.0,United Kingdom
10,536368,22913,RED COAT RACK PARIS FASHION,3,01/12/10 08:34,4.95,13047.0,United Kingdom
11,536368,22912,YELLOW COAT RACK PARIS FASHION,3,01/12/10 08:34,4.95,13047.0,United Kingdom
12,536368,22914,BLUE COAT RACK PARIS FASHION,3,01/12/10 08:34,4.95,13047.0,United Kingdom
13,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,01/12/10 08:34,1.69,13047.0,United Kingdom
14,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,01/12/10 08:34,2.10,13047.0,United Kingdom

convert "?" to NaN... usingreplace()method.....syntax:=replace(A,B, inplace="True")....repalce A to B

In [22]:
import numpy as np

# replace "?" to NaN
data.replace("?", np.nan, inplace = True)
data.head(2)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01/12/10 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01/12/10 08:26,3.39,17850.0,United Kingdom

Evaluating for Missing Data
The missing values are converted by default. We use the following functions to identify these missing values. There are two methods to detect missing data:

.isnull()
.notnull()
The output is a boolean value indicating whether the value that is passed into the argument is in fact missing data

In [23]:
missing_data = data.isnull()
missing_data.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False

Using a for loop in Python, we can quickly figure out the number of missing values in each column. As mentioned above, "True" represents a missing value and "False" means the value is present in the dataset.  In the body of the for loop the method ".value_counts()" counts the number of "True" values.

In [24]:
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

Invoice
Invoice
False    541910
Name: count, dtype: int64

StockCode
StockCode
False    541910
Name: count, dtype: int64

Description
Description
False    540409
True       1501
Name: count, dtype: int64

Quantity
Quantity
False    541910
Name: count, dtype: int64

InvoiceDate
InvoiceDate
False    541910
Name: count, dtype: int64

Price
Price
False    541910
Name: count, dtype: int64

Customer ID
Customer ID
False    406830
True     135080
Name: count, dtype: int64

Country
Country
False    541910
Name: count, dtype: int64

Calculate the mean value for the column

mean_variable = dataFrame["col"].astype("float").mean(axis =0)
print("Mean item price:", mean_variable).....this code calculate mean of column and print it

In [25]:
import pandas as p
data = p.read_csv("dataset/supermarket_data.csv")
data.head(15)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01/12/10 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01/12/10 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01/12/10 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01/12/10 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01/12/10 08:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,01/12/10 08:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,01/12/10 08:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,01/12/10 08:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,01/12/10 08:28,1.85,17850.0,United Kingdom
9,536368,22960,JAM MAKING SET WITH JARS,6,01/12/10 08:34,4.25,13047.0,United Kingdom
10,536368,22913,RED COAT RACK PARIS FASHION,3,01/12/10 08:34,4.95,13047.0,United Kingdom
11,536368,22912,YELLOW COAT RACK PARIS FASHION,3,01/12/10 08:34,4.95,13047.0,United Kingdom
12,536368,22914,BLUE COAT RACK PARIS FASHION,3,01/12/10 08:34,4.95,13047.0,United Kingdom
13,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,01/12/10 08:34,1.69,13047.0,United Kingdom
14,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,01/12/10 08:34,2.10,13047.0,United Kingdom

In [26]:
mean = data["Price"].astype("float").mean(axis =0)
print("mean of the price:",mean)

mean of the price: 4.611138332933512

replace Nan to mean

data["Price"].replace(np.nan, mean, inplace=True)...but there is no missing data show replacement not done

BINNING:--->Binning is a process of transforming continuous numerical variables into discrete categorical 'bins' for grouped analysis
.....we perform binng in price column ..OK

In [30]:
import numpy as np
data["Price"]=data["Price"].astype(int, copy=True)
bins = np.linspace(min(data["Price"]), max(data["Price"]),4)
grp_Name = ['Low','Medium','High']
data['Price-binned'] = p.cut(data['Price'], bins, labels=grp_Name, include_lowest=True )
data[['Price','Price-binned']].head(20)

C:\Users\303421\AppData\Local\Temp\ipykernel_16848\3522508766.py:2: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  data["Price"]=data["Price"].astype(int, copy=True)

    Price Price-binned
0       2          Low
1       3          Low
2       2          Low
3       3          Low
4       3          Low
5       7          Low
6       4          Low
7       1          Low
8       1          Low
9       4          Low
10      4          Low
11      4          Low
12      4          Low
13      1          Low
14      2          Low
15      2          Low
16      3          Low
17      1          Low
18      4          Low
19      4          Low

In [36]:
max(data["Price"])
data.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Price-binned
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01/12/10 08:26,2,17850.0,United Kingdom,Low
1,536365,71053,WHITE METAL LANTERN,6,01/12/10 08:26,3,17850.0,United Kingdom,Low
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01/12/10 08:26,2,17850.0,United Kingdom,Low
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01/12/10 08:26,3,17850.0,United Kingdom,Low
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01/12/10 08:26,3,17850.0,United Kingdom,Low

In [1]:
for maxi in missing_data.max(data["Price"]).values.tolist():
    print(maxi)

NameError: name 'missing_data' is not defined